### ISSUE TITLE
Not working in Magento 2.2.1

### ISSUE THREAD

**Issue by Draidel** [mageprince/magento2-buynow#11]
Hello,
 I followed the installation guide but it doesnt show up neither in the storefront nor in the configuration page.

![image](https://user-images.githubusercontent.com/11020595/36856904-edaae2b4-1d55-11e8-9fe5-014e630d6f5e.png)

I also believe that it should be found in **/app/etc/config.php** but its not there.

**Comment by mageprince** [comment]
@Draidel Thanks for posting issue.
I installed this module in default Magento 2.2.1 with the latest code and it's working fine without any issue. Please check the screenshot.

![configuration settings](https://user-images.githubusercontent.com/24751863/36859219-ab236648-1da3-11e8-8799-2213a3274b21.png)

**Comment by Draidel** [comment]
Can you help me to find out what is wrong ?

 How is it calling the module in /app/etc/config.php ?

**Comment by mageprince** [comment]
**'Prince_Buynow' => 1** in config.php.
1. Download repo from github
2. Copy repo content in app/code/Prince/Buynow folder
3. Run php bin/magento setup:upgrade
4. Run php bin/magento setup:static-content:deploy
5. Run php bin/magento cache:flush
