### ISSUE TITLE
how i get it in custom block at homepage

### ISSUE THREAD

**Issue by eldaly** [mageprince/magento2-buynow#12]
how i get it in custom block at homepage ??

**Comment by mageprince** [comment]
@eldaly Thank you for posting issue. 
Can you please explain in details with description.

**Comment by eldaly** [comment]
i want add buy now button in homepage produts block ?

**Comment by eldaly** [comment]
?

**Comment by eldaly** [comment]
im add this code but not go to checkout page
`        <?php if ($_item->isSaleable()) : ?>
                                        <?php
                                        $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()]);
                                        $BuyData = json_decode($postData);
                                        ?>
                                        <?php $helper = $this->helper("Prince\Buynow\Helper\Data"); ?>
                                        <?php $buttonTitle = $helper->getConfig('buynow/general/buttontitle'); ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_item); ?>


                                        <div class="product-item-inner buynow">
                                            <form  action="<?php echo $BuyData->action; ?>"
                                                  id="product_addtocart_form_<?php echo $_item->getEntityId(); ?>"
                                                  method="post">
                                                <input type="hidden"
                                                       name="product"
                                                       value="<?php echo $BuyData->data->product; ?>">
                                                <input type="hidden"
                                                       name="<?php /* @noEscape */ echo 'uenc'; ?>"
                                                       value="<?php echo $BuyData->data->uenc; ?>">
                                                <?php echo $block->getBlockHtml('formkey')?>
                                                <button type="submit"
                                                        title="<?php echo $block->escapeHtml(__($buttonTitle)); ?>"
                                                        class="action tocart buynow primary"
                                                        data-mage-init='
                    {
                        "Prince_Buynow/js/buy-now": {
                            "form": "#product_addtocart_form_<?php echo $_item->getEntityId(); ?>"
                        }
                    }
                '>
                                                    <span><?php /* @noEscape */ echo __($buttonTitle) ?></span>
                                                </button>
                                            </form>
                                        </div>
                                    <?php endif; ?>`

**Comment by mageprince** [comment]
Add buynow block after add to cart button like

    $buyNowHtml = $this->getLayout()
         ->createBlock('Prince\Buynow\Block\Product\ListProduct')
         ->setProduct($_item)
         ->setTemplate('Prince_Buynow::buynow-list.phtml')
         ->toHtml();
    echo $buyNowHtml;

Check this answer for more details: https://magento.stackexchange.com/a/220680/35758

**Comment by eldaly** [comment]
thank you i will try this

**Comment by niezw** [comment]
> Add buynow block after add to cart button like
> 
> ```
> $buyNowHtml = $this->getLayout()
>      ->createBlock('Prince\Buynow\Block\Product\ListProduct')
>      ->setProduct($_item)
>      ->setTemplate('Prince_Buynow::buynow-list.phtml')
>      ->toHtml();
> echo $buyNowHtml;
> ```
> 
> Check this answer for more details: https://magento.stackexchange.com/a/220680/35758


Whether it works properly at 1.3.0 ??? Show blank in my project,hope to get your help. Thank you.

**Comment by ashu2389P** [comment]
Hey, @niezw  Did you find code to add in the custom block? 

The above code is not working for me, too.

**Comment by niezw** [comment]
> Hey, @niezw Did you find code to add in the custom block?
> 
> The above code is not working for me, too.

in the 1.3.0,The project changed its path.
you can try 
`<?php echo $this->getLayout()->createBlock("Mageprince\BuyNow\Block\Product\ListProduct")->setProduct($product)->setTemplate("Mageprince_BuyNow::buynow-list.phtml")->toHtml(); ?>`

**Comment by ashu2389P** [comment]
It's working for list.phtml but in Porto Magento 2 theme there is owl-list.phtml and this code is not working for owl-list.phtml

[2020-06-01 15:08:00] main.CRITICAL: Warning: Use of undefined constant php - assumed 'php' (this will throw an Error in a future version of PHP) in /home/fabkraft/public_html/app/design/frontend/Smartwave/porto_child/Smartwave_Filterproducts/templates/owl_list.phtml on line 271 {"exception":"[object] (Exception(code: 0): Warning: Use of undefined constant php - assumed 'php' (this will throw an Error in a future version of PHP) in /home/fabkraft/public_html/app/design/frontend/Smartwave/porto_child/Smartwave_Filterproducts/templates/owl_list.phtml on line 271 at /home/fabkraft/public_html/vendor/magento/framework/App/ErrorHandler.php:61)"} []

**Comment by ashu2389P** [comment]
Issue Fixed. Thanks :)
