### ISSUE TITLE
Buy Now button not redirected to checkout page

### ISSUE THREAD

**Issue by Dushant1011** [mageprince/magento2-buynow#14]
@mageprince I am using magento 2.0.6 and my prince buy now extension version is 1.0. From last 1 and 1/2 year . Now buy now button on product details page not redirected to checkout page .

**Comment by mageprince** [comment]
@Dushant1011 I recently made few changes with this module. You can check these commits [Commits](https://github.com/mageprince/magento2-buynow/commits/master) or download the latest repository code.
