### ISSUE TITLE
Buy Now not working for ajax loaded products

### ISSUE THREAD

**Issue by kfeibel92** [mageprince/magento2-buynow#15]
Hello,

we are using your extension for our shop. We added a new Infinitiy Scroll to the catalog Page, which reloads more products with ajax. And our used theme has product Lists on the homepage, which loads products via ajax after the user clicked a categorie.
The problem now is, that the - with ajax loaded - products (in both cases) have the Buy now button, but it is not working right. A click on the button just adds the Product to the cart or simple doesnt do anything.

On the Product Category Page the button is added with your extension and on the Homepage, the button got added directly with programming.

I hope you can help me to get the Buy now also work for ajax loaded Products.

Best Regards

**Comment by mageprince** [comment]
Hi, @kfeibel92 Thanks for your report.
This module is not compatible with infinity scroll module in the list page. Becuase I use knockout js in this module and knockout js is not initialized in ajax response. Maybe I will solve this issue in the future version of this module. I hope you understand.
Thank You.
