### ISSUE TITLE
can't work with aheadwork ajax cart pro plugin

### ISSUE THREAD

**Issue by benyang2015** [mageprince/magento2-buynow#19]

**Comment by mageprince** [comment]
@benyang2015 Thank you for your report. Please provide more description with the steps to reproduce the issue.

**Comment by benyang2015** [comment]
install aheadwork ajax cart pro，on product page，click buy now button，popup windows not go to the checkout page
if work fine click the buy now will go to the checkout page not popup the windows

**Comment by mageprince** [comment]
@benyang2015 Please send me ajax cart pro module on mail.mageprince@gmail.com to check the issue.

**Comment by benyang2015** [comment]
ajax cart pro already sent to you email

**Comment by mageprince** [comment]
@benyang2015 Can you please send again.

**Comment by benyang2015** [comment]
already send to your email

**Comment by mageprince** [comment]
@benyang2015 I have installed aheadwork ajax cart pro and checked that this module fires their events on form submit also buy now module working on form submit. So ajax cart module not compatible with buy now module.

**Comment by benyang2015** [comment]
how to solve this problem
