### ISSUE TITLE
Buy now button  not enabled category listing page magento 2.2.5

### ISSUE THREAD

**Issue by shihascorecode** [mageprince/magento2-buynow#21]
Hi 

I have installed this buynow button module on fresh magento 2.2.5 . its working fine product view page. but  buynow button not display in category listing page,  I have already enable this module On List Page option from the admin backend...  Please help me!

please check below link for the clarification 

category listing page : 

https://plugtip.com/gear.html

Thanks 
Shihas 
![screenshot 315](https://user-images.githubusercontent.com/43324713/45601527-d386ff80-ba2b-11e8-85cd-ec3f58cc4b45.png)

**Comment by mageprince** [comment]
Hi @shihascorecode Thanks for your report. 
The link which you provided is category landing page, not category page. It's working as accepted Please check category page: https://plugtip.com/gear/bags.html

**Comment by shihascorecode** [comment]
Hi @mageprince 

I have installed your module in https://www.etfio.in/ 

Buy now button not enabled in listing, please check

https://www.etfio.in/buy-books-online.html


Buy now Button Enabled in products details page... 

https://www.etfio.in/kas-cracker-i-ii.html

Please help me !

thanks for your Support

Shihas
