### ISSUE TITLE
Buy now button not enabled category listing page magento 2.2.5

### ISSUE THREAD

**Issue by shihascorecode** [mageprince/magento2-buynow#22]
Hi

I have installed this buynow button module on fresh magento 2.2.5 . its working fine product view page. but buynow button not display in category listing page, I have already enable this module On List Page option from the admin backend... Please help me!

please check below link for the clarification

category listing page :

https://www.etfio.in/buy-books-online.html

Thanks

**Comment by antoniocarrion** [comment]
Hi,

i found the same issue on Magento 2.2.6

Any way to fix this?
Thanks in advance

**Comment by mageprince** [comment]
@shihascorecode Please check third party modules which override product list block or disable all third party modules and check.
