### ISSUE TITLE
Buy now button is not showing at category page and css issue at detailes page

### ISSUE THREAD

**Issue by tejabhagavankollepara** [mageprince/magento2-buynow#23]
Hello Prince,
I just installed on magento2.2.6 website.
Buy now is appeared at product detailed page and its working great.
But, Not showing at category page and having css related issue at product details page.

1. Category page : [http://www.depoto.com/vizag/hand-tools/adjustable-spanners/adjustable-spanners-phosphate-finish.html](http://www.depoto.com/vizag/hand-tools/adjustable-spanners/adjustable-spanners-phosphate-finish.html)

2. Product details page : [http://www.depoto.com/vizag/long-nose-plier-new.html](http://www.depoto.com/vizag/long-nose-plier-new.html)

And what is the Rest api for this extension to built mobile application?

Thanks

**Comment by mageprince** [comment]
@tejabhagavankollepara As you have used a custom theme you need to set little design for buynow button.
