### ISSUE TITLE
Module fails in product view with configurable products Magento 2.2.6

### ISSUE THREAD

**Issue by antoniocarrion** [mageprince/magento2-buynow#24]
Hi,
i'm facing this error in product view, when the product is configurable:
 **PHP Fatal error:  Uncaught Error: Call to a member function isSaleable() on null in /var/www/html/vendor/mageprince/module-buynow/view/frontend/templates/buynow-list.phtml:4**

It works fine with simple products.

What can i do to fix this issue?
Thanks in advance,
Antonio

**Comment by mageprince** [comment]
@antoniocarrion Please use `buynow-view.phtml` for product view page.

`<block class="Magento\Catalog\Block\Product\View"
                   name="product.buynow"
                   template="Prince_Buynow::buynow-view.phtml"
                   before="-" ifconfig="buynow/general/enable_view"/>
`
