### ISSUE TITLE
shop.com/checkout/noroute after click "Buy Now"

### ISSUE THREAD

**Issue by SPL3S** [mageprince/magento2-buynow#25]
Magento ver. 2.2.7
Theme: Solwin Freego
Browser:  Chrome v71.0.3578.98

After clicking on "Buy now" URL parameters change to:
 shop.com/checkout/#size=167&color=49 
and it seems to be loading the Checkout page for a second, but then redirects to 404

**Comment by mageprince** [comment]
@SPL3S This is a third party theme related issue. This module is working fine with the default Magento theme. Please check this file for more details: [L81](https://github.com/mageprince/magento2-buynow/blob/6a3b7cc6fbf816c892d161d0c5dd59a5396e8007/Controller/Cart/Add.php#L81)
