### ISSUE TITLE
Add to cart button and Buy now button are of different sizes.

### ISSUE THREAD

**Issue by anurag3singh** [mageprince/magento2-buynow#26]
Add to cart button and Buy now button are of different sizes in Mobile site, but in normal desktop site it is ok. Please help and resolve. Thanks in advance.

**Comment by anurag3singh** [comment]
Thanks for support. Can you please tell me which file i have to change?
I am a newbie in Megento.
Regards.

**Comment by mageprince** [comment]
@anurag3singh Change css filr `buynow.css` from `view/frontend/web/css`

**Comment by anurag3singh** [comment]
i did it but it doesnot work. please see loopkart.com products.

**Comment by mageprince** [comment]
@anurag3singh I have seen that you enabled the merging CSS. Run the following command to take effect on new changes. And check merge CSS for new changes.
`php bin/magento s:s:d`

**Comment by anurag3singh** [comment]
Sir,
Now on clicking buynow button (only in configurable products), the checkout
shows an error. Please check here.
https://www.loopkart.com/women/ethnic-wear.html
When you select size and click Buy Now, the Checkout redirects and shows
error.
Please help.
Grateful to you.
Thanks & Regards.

**Comment by mageprince** [comment]
@anurag3singh There are something issue with any third party module or theme. Becuase it adds the size to the end of the checkout url. Like: `https://www.loopkart.com/checkout/#size=167`

**Comment by anurag3singh** [comment]
Hello Sir,
Even at ../#size=167 it is showing error. Please help. It's only with
Configurable products. What could possibly cause this error.
Thanks and regards.
