### ISSUE TITLE
Buy now button not showing on Product Compare Page

### ISSUE THREAD

**Issue by bhrugeshpatel** [mageprince/magento2-buynow#27]
Hello,

I have face one issue, we try to compare three product and that page I can't see buy now button.

So, can you please help for display and working buy now button on Product Compare Page ?

In other pages buy now button is working verywell

Thanks in advance...

Regards,
Bhrugesh

**Comment by bhrugeshpatel** [comment]
Is there any solution ?

**Comment by mageprince** [comment]
@bhrugeshpatel We not added buy now button in compare list. You can use buynow button template in compare list file. So override compare list to buy now module `/vendor/magento/module-catalog/view/frontend/templates/product/compare/list.phtml` now use before code after addtocart button of compare product.

`<?php echo $this->getLayout()->createBlock("Prince\Buynow\Block\Product\ListProduct")->setProduct($item)->setTemplate("Prince_Buynow::buynow-list.phtml")->toHtml();
?>`
