### ISSUE TITLE
How to link button to cart

### ISSUE THREAD

**Issue by josiahglassone** [mageprince/magento2-buynow#29]
How can I link the button to the shopping cart page instead of the checkout/#shipping page?

**Comment by mageprince** [comment]
Hi @josiahglassone ,
Change line `$this->goBack($baseUrl.'checkout/', $product);` To `$this->goBack($baseUrl.'checkout/cart/', $product);` from line [#L81](https://github.com/mageprince/magento2-buynow/blob/master/Controller/Cart/Add.php#L81)

**Comment by josiahglassone** [comment]
Works great! Thank you very much!
