### ISSUE TITLE
Buy Now Button not redirected to checkout page

### ISSUE THREAD

**Issue by somunelavalli** [mageprince/magento2-buynow#30]
After Upgrading to Magento 2.3.2
When i click on BuyNow Button it is not redirected to checkout page

**Comment by mageprince** [comment]
@somunelavalli This module is working fine with default Magento 2.3.2. Please check other third party extension or test with default Magento setup and let us know if still issue persistence.

**Comment by mageprince** [comment]
@somunelavalli This issue has been solved now. Please download the latest version of this module or check commit: https://github.com/mageprince/magento2-buynow/commit/c3ea573811f9b4098006804a82c309453259207f
