### ISSUE TITLE
Buynow not working, after clicking buy now button its redirecting to checkout without product.

### ISSUE THREAD

**Issue by sudhakare29** [mageprince/magento2-buynow#32]
Showing empty checkout cart.

You have no items in your shopping cart.
Click here to continue shopping.

**Comment by volanar** [comment]
I have another problem. Module installed mageplaza One Step Checkout and when clicking the button throws are not on the checkout page of the module. There is a transition to the standard checkout page

**Comment by mageprince** [comment]
> Showing empty checkout cart.
> 
> You have no items in your shopping cart.
> Click here to continue shopping.

@sudhakare29 Please check this line: [L81](https://github.com/mageprince/magento2-buynow/blob/6a3b7cc6fbf816c892d161d0c5dd59a5396e8007/Controller/Cart/Add.php#L81)
In your case, you are not getting a product object. Please check with disabling other third part modules or check it with default Magento setup.

**Comment by mageprince** [comment]
> I have another problem. Module installed mageplaza One Step Checkout and when clicking the button throws are not on the checkout page of the module. There is a transition to the standard checkout page

@volanar Sorry, This module is not tested with mageplaza one step checkout.

**Comment by mageprince** [comment]
@sudhakare29 This issue has been solved now. Please download the latest version of this module or check commit: https://github.com/mageprince/magento2-buynow/commit/c3ea573811f9b4098006804a82c309453259207f
