### ISSUE TITLE
Buy now not working for configureable products, magento 2.3.2

### ISSUE THREAD

**Issue by saniish** [mageprince/magento2-buynow#33]
Buy now is working as it should for simple products, but when there is configureable product, the buy now button is able to successfully add the specify child product to the cart, but is not able to redirect. After clicking on url the product is added to cart and then this url - example.com/#color=32
Then it throws a 404 error with this url - example.com/checkout/noroute
I think it is failing to redirect. How to solve this issue?
I am using basic Luna theme with magento 2.3.2

**Comment by mageprince** [comment]
@saniish Thank you posting an issue. This issue has been solved now. Please download latest version of this module or check commit: https://github.com/mageprince/magento2-buynow/commit/c3ea573811f9b4098006804a82c309453259207f
