### ISSUE TITLE
Not Redirecting to Checkout Page on second time

### ISSUE THREAD

**Issue by selisc** [mageprince/magento2-buynow#34]
Hi,

I have installed & configured this module and its working for first time and its not redirecting to the checkout page when I proceed Buy now button on second time on the same product?

**Steps to Reproduce the Issue.**
1. Go to Product page and click on Buy Now button and its goes to Checkout page 
2. After that Go to same product page and click on Buy Now button but its not goes to Checkout Page and its loading the same product page instead of going to Checkout page.

**Expected Result :**
When we click on the Buy Now button on product page then it should always redirect to Checkout Page

Can you please check it?

Thanks.

**Comment by mageprince** [comment]
@selisc This module is tested with Magento 2.2.x and Magento 2.3.x version. Please check following scenario to debug the issue.

1. Please check product configurations like product should not restrict to only 1 qty to cart etc...
2. Check for any console js errors
3. Add exit to the execute() function of controller and debug: https://github.com/mageprince/magento2-buynow/blob/master/Controller/Cart/Add.php
4. Uninstall all third party modules and check
5. Check with default Magento Setup
