### ISSUE TITLE
Buy now not working on list page

### ISSUE THREAD

**Issue by rajtiwarikmw** [mageprince/magento2-buynow#35]
After enable list page option "Yes"... it not working. after add the code on list page ... 

I am using magento 2.3.2. 
can u plz help ..

**Comment by mageprince** [comment]
@rajtiwarikmw This module is tested with Magento 2.2.x and Magento 2.3.x version. Please check the following scenario to debug the issue.

1. Check with default Magento Luma Theme
2. Uninstall all third party modules and check
3. Check with default Magento Setup
