### ISSUE TITLE
Custom code for Buy Now button to put in File 

### ISSUE THREAD

**Issue by ashu2389P** [mageprince/magento2-buynow#40]
$buyNowHtml = $this->getLayout()
     ->createBlock('Prince\Buynow\Block\Product\ListProduct')
     ->setProduct($_item)
     ->setTemplate('Prince_Buynow::buynow-list.phtml')
     ->toHtml();
echo $buyNowHtml; 

I want this code for Magento 2.3 with Your Latest version of Extension. 

There is an issue in "createBlock" line and in "setPorduct" line, I think.

**Comment by mageprince** [comment]
Hi @ashu2389P Here is the latest code of buynow button

```
$buyNowHtml = $this->getLayout()
    ->createBlock('Mageprince\BuyNow\Block\Product\ListProduct')
    ->setProduct($_item)
    ->setTemplate('Mageprince_BuyNow::buynow-list.phtml')
    ->toHtml();
echo $buyNowHtml;
```

Here is the screenshot of sample code of usage

![image](https://user-images.githubusercontent.com/24751863/93671613-00aa9480-fac2-11ea-833b-5bd2c1d2a2fb.png)
