### ISSUE TITLE
Buy Now button not redirecting to onestep checkout page

### ISSUE THREAD

**Issue by deepak66gupta** [mageprince/magento2-buynow#41]
Dear Team
I am using magento 2.3.2 and used buy now button with one step checkout page from Mageplaza. The difficulty I am facing is when click on buy now button it redirects me to Magento default 2 step checkout not redirecting to Mageplaza one step checkout while checkout from shopping cart working fine and redirecting to one step checkout

Pl solve this issue

**Comment by mageprince** [comment]
Hi @deepak66gupta 
Please change redirection url from `checkout` to onestep checkout in file https://github.com/mageprince/magento2-buynow/blob/35c5e012c03eaa18d991966b2be6883cffa6c18a/Controller/Cart/Add.php#L71

**Comment by deepak66gupta** [comment]
Thanks it works

 

Deepak Gupta
