### ISSUE TITLE
Buy now button change to Add to Cart

### ISSUE THREAD

**Issue by deepak66gupta** [mageprince/magento2-buynow#43]
Dear Team

We are facing an issue when using this Buy now button. Once click on Add to Cart Buy now button also gets changed to Add to Cart. Can some one guide me why its happening. you can view it here

https://emaven.in/academictest/orient-black-swan-sadabahar-hindi-likhai-book-b.html

**Comment by mageprince** [comment]
Hi @deepak66gupta Thank you for your patience. This issue is resolved now.
Related commit: https://github.com/mageprince/magento2-buynow/commit/44f8bfc63bfb814c5cb4160f94e3aa374abfda6f
