### ISSUE TITLE
Bug in buy-now.js

### ISSUE THREAD

**Issue by nguyentung9820** [mageprince/magento2-buynow#47]
i found a bug in js, it's must be element.form

define([
    'jquery'
], function ($) {
    "use strict";
    return function (config, element) {
        $(element).click(function () {
            var form = $(element.form);
            // change form action
            var baseUrl = form.attr('action'),
                buyNowUrl = baseUrl.replace('checkout/cart/add', 'buynow/cart/add');
            console.log(baseUrl);
            form.attr('action', buyNowUrl);

            form.trigger('submit');

            // set form action back
            form.attr('action', baseUrl);

            return false;
        });
    }
});

**Comment by mageprince** [comment]
Hi @nguyentung9820 This is fixed. Please check latest release: [Release 1.4.0](https://github.com/mageprince/magento2-buynow/archive/refs/tags/1.4.0.zip)
