### ISSUE TITLE
For Configurable product what we can do?

### ISSUE THREAD

**Issue by harishkhant** [mageprince/magento2-buynow#50]
it redirects the list page to the product page after clicking the buy now button.
 
 It shows "You need to choose options for your item "
 https://www.loom.com/share/d0d675dc59b740b787c72502048b1a92

**Comment by harishkhant** [comment]
@mageprince

**Comment by harishkhant** [comment]
@mageprince also one more thing is, on click buy now button we have seen that add cart button text changed "Added..".

if we need to change text during Buy now button click the event. Are any changes to the js file?
![Screenshot from 2022-09-26 15-20-43](https://user-images.githubusercontent.com/64633051/192247000-67061fc6-c0b4-4457-9f66-cbd8997fe02d.png)

**Comment by mageprince** [comment]
Hi @harishkhant Both issue are fixed. Please download latest release: [Release 1.4.0](https://github.com/mageprince/magento2-buynow/archive/refs/tags/1.4.0.zip)
