### ISSUE TITLE
Not working with Ultimo theme on Magento 2.2

### ISSUE THREAD

**Issue by vinaykumar9999** [mageprince/magento2-buynow#6]
Is there any fix for ultimo theme, Using Magento 2.2

Please find the attached list.phtml and catalog_product.view.xml files of ulitmo theme

I have tried a lot but not coming on product page.

Please help out with the code so that it will display next to "add to cart button"

[catalogproductview - listphtml.zip](https://github.com/mageprince/magento2-buynow/files/1383660/catalogproductview.-.listphtml.zip)

**Comment by mageprince** [comment]
Hi @vinaykumar9999,
I use **`product.info.addto`** block to adding buynow button in product view page. But product view page of ultimo theme is fully customized and this block is not available in product view page. 

So you can call buynow button phtml file to `product/view.phtml` of ultimo theme by this code:

**Add this code in view.phtml file after addtocard button:**
`<?php echo $this->getLayout()->createBlock("Magento\Catalog\Block\Product\View")->setTemplate("Prince_Buynow::buynow-view.phtml")->toHtml(); ?>`

**Comment by vinaykumar9999** [comment]
Hi Prince

Thanks for the quick reply, I have added the code to the view.phtml of ultimo theme. But still Buy Now Button is not showing up.

Please find the attached view.phtml with the added code

I have tried with both the methods to call block <?php echo $this and <?php echo $block 

But still no luck
[view.zip](https://github.com/mageprince/magento2-buynow/files/1385223/view.zip)

**Comment by vinaykumar9999** [comment]
Hi Prince

It is working now 

Thanks for the help.

**Comment by mageprince** [comment]
Just apply `float:left` in css to buy now button class.
